openapi: 3.0.0
info:
  title: API Simulada - Gestión de Reservas
  version: "1.0"
  description: Documentación simulada de clientes y reservaciones activas.

tags:
  - name: Reservas
    description: Operaciones simuladas relacionadas con reservas

paths:
  /clientes:
    post:
      tags:
        - Reservas
      summary: Crear una nueva Cliente
      description: Simula la creación de un nuevo cliente con los datos proporcionados.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Guest'
      responses:
        '201':
          description: Cliente creado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Guest'
        '400':
          description: Datos de reserva inválidos

    get:
      tags:
        - Reservas
      summary: Obtener todos los clientes
      description: Simula la obtención de todos los clientes registrados
      responses:
        '200':
          description: Lista de clientes obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Guest'
        '500':
          description: Error interno al obtener los clientes

  /reservas/activas:
    get:
      tags:
        - Reservas
      summary: Obtener reservaciones activas
      description: Devuelve una lista de reservaciones que están en estado ACTIVA.
      responses:
        '200':
          description: Lista de reservaciones activas obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reservation'
        '500':
          description: Error al obtener las reservaciones

components:
  schemas:
    Guest:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        nombre:
          type: string
          example: Jhon
        email:
          type: string
          format: email
          example: cliente@hotel.com
        telefono:
          type: string
          example: "2323423423"
        fechaRegistro:
          type: string
          format: date-time
          example: "2025-08-06T22:00:00"

    Reservation:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        guestId:
          type: integer
          example: 1
        roomId:
          type: integer
          example: 101
        fechaCheckIn:
          type: string
          format: date
          example: "2025-08-07"
        fechaCheckOut:
          type: string
          format: date
          example: "2025-08-09"
        numeroHuespedes:
          type: integer
          example: 2
        montoTotal:
          type: number
          format: decimal
          example: 300.00
        estado:
          type: string
          enum: [ACTIVA, CANCELADA, FINALIZADA]
          example: ACTIVA
        fechaCreacion:
          type: string
          format: date-time
          example: "2025-08-06T20:00:00"
